[package]
name = "pipemixer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
pipewire = "0.8.0"
ratatui = "0.26.1"
