[package]
name = "fallout-save-editor"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
flate2 = "1.0"
bitflags = "2.5.0"
clap = { version = "4.5.7", features = ["derive"] }
